# Generated by Django 3.2.6 on 2021-08-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=45)),
                ('amount', models.FloatField(default=1.0)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('site', models.CharField(max_length=45)),
            ],
        ),
    ]
