version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./static/:/app/static/
    ports:
      - 9000:8000
    env_file:
      - deploy/conf.env
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge